language: c
compiler: 
  - gcc
  - clang
os: linux

before_script: aclocal && autoheader && libtoolize --copy && autoconf && automake --gnu --add-missing --copy && ./configure
script: make && make check
